[[stack]]
name = "demo-nginx"
description = "Nginx deployed from GitHub with Komodo Resource Sync"
tags = ["demo", "gitops"]


deploy = true

[stack.config]
server = "komodo-periphery"
run_directory = "/opt/komodo/stacks/demo-nginx"

repo = "mrnim94/komodo-gitops-demo"
branch = "master"


git_provider = "github.com"
git_account = "mrnim94"

file_paths = ["nginx-demo/compose.yaml"]